### ISSUE TITLE
Unable to connect to Camera Service

### ISSUE THREAD

**Issue by aftabsikander** [pixo-vin/android-sdk#10]
I have created sample app using your trial version SDK followed every single step of developer's documentation. However, I am getting this error on every single device I have tested on. I have replaced original package name with dummy package just to share logs with you. 

**List of devices** and IDE version details and **MainActivity** code are shared as well.

**Main Activity**

```
package com.app.example;

import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.widget.AppCompatTextView;

import com.pixotech.android.scanner.library.ScannerActivity;

import butterknife.BindView;

public class MainActivity extends ScannerActivity  {

    @Nullable
    @BindView(R.id.vinTextView)
    public AppCompatTextView vinTextView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        addLayout(R.layout.activity_main);
    }

    @Override
    public void handleDecode(String s) {
        vibrate();
        vinTextView.setText(s);
        startScan();
    }
}
```
**XML layout file**

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextView
        android:id="@+id/vinTextView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center_horizontal"
        android:textSize="32sp" />

    <com.pixotech.android.scanner.library.DataMatrixLaserView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

</RelativeLayout>
```
List of Devices which were used to produce this issue

**Device # 1**

```
Brand: Google
DeviceModel: Nexus 5
Product: hammerhead
Manufacturer: LGE
Android Version: 6.0.1
```

**Device # 2**

```
Brand: Samsung
DeviceModel: SM-G530H
Product: fortuna3gxx
Manufacturer: Samsung
Android Version: 6.0.1
```

**Device # 3**

```
Brand: Samsung
DeviceModel: SM-G530H
Product: fortuna3gxx
Manufacturer: Samsung
Android Version: 5.0
```

**IDE Version**
```
Android Studio 3.0 RC 2
Build #AI-171.4402976, built on October 18, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Logs Error**
```
com.app.example W/CameraBase: An error occurred while connecting to camera: 0
com.app.example W/System.err: java.lang.RuntimeException: Fail to connect to camera service
com.app.example W/System.err:     at android.hardware.Camera.<init>(Camera.java:495)
com.app.example W/System.err:     at android.hardware.Camera.open(Camera.java:341)
com.app.example W/System.err:     at com.pixotech.android.scanner.library.BarcodeScanner.l(SourceFile:107)
com.app.example W/System.err:     at com.pixotech.android.scanner.library.BarcodeScanner.c(SourceFile:78)
com.app.example W/System.err:     at com.pixotech.android.scanner.library.BarcodeScanner.<init>(SourceFile:64)
com.app.example W/System.err:     at com.pixotech.android.scanner.library.ScannerActivity.onCreate(SourceFile:24)
com.app.example W/System.err:     at com.app.example.MainActivity.onCreate(MainActivity.java:19)
com.app.example W/System.err:     at android.app.Activity.performCreate(Activity.java:6251)
com.app.example W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
com.app.example W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
com.app.example W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
com.app.example W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
com.app.example W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
com.app.example W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
com.app.example W/System.err:     at android.os.Looper.loop(Looper.java:148)
com.app.example W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
com.app.example W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
com.app.example W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
com.app.example W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
com.app.example D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
com.app.example I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
com.app.example I/OpenGLRenderer: Initialized EGL, version 1.4
com.app.example W/CameraBase: An error occurred while connecting to camera: 0
com.app.example W/System.err: java.lang.RuntimeException: Fail to connect to camera service
com.app.example W/System.err:     at android.hardware.Camera.<init>(Camera.java:495)
com.app.example W/System.err:     at android.hardware.Camera.open(Camera.java:341)
com.app.example W/System.err:     at com.pixotech.android.scanner.library.BarcodeScanner.l(SourceFile:107)
com.app.example W/System.err:     at com.pixotech.android.scanner.library.BarcodeScanner.c(SourceFile:78)
com.app.example W/System.err:     at com.pixotech.android.scanner.library.BarcodeScanner.<init>(SourceFile:64)
com.app.example W/System.err:     at com.pixotech.android.scanner.library.ScannerActivity.onResume(SourceFile:33)
com.app.example W/System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
com.app.example W/System.err:     at android.app.Activity.performResume(Activity.java:6327)
com.app.example W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
com.app.example W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
com.app.example W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)
com.app.example W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
com.app.example W/System.err:     at android.os.Looper.loop(Looper.java:148)
com.app.example W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
com.app.example W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
com.app.example W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
com.app.example W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by pixovin** [comment]
Hello Aftab,

Thank you for reporting this issue. One of our developers will look into it
and we will be in touch with questions or next steps soon.

Warmly,


*Shawna Culp*

Pixo *|* Business and Product Coordinator
121 W. Goose Alley
Urbana, IL 61801
(217) 344-0444
pixotech.com
pixoVIN.com

**Comment by aftabsikander** [comment]
I have uploaded the video file for the developer to debug the issue, it can be downloaded from this [link](https://drive.google.com/file/d/0BzFEs0fNIo-Dd2RGZUNqeHJ6SHM/view).

**Comment by youngest** [comment]
It looks like your application does not have permission to access the camera. When the targetSdkVersion in your app's build.gradle file is set to 23 or above then your application must request certain permissions directly from the user, it is no longer enough to simply list those permissions in the application manifest. The camera permission falls into this category.

This article provides a good guide to requesting permissions at runtime: https://developer.android.com/training/permissions/requesting.html

**Comment by aftabsikander** [comment]
@youngest  My assumption was permission would be handled by this SDK internally, Yes you were correct due to permission I was getting this error. It would be great if runtime permission should be handled by SDK and prompted user with meaningful errors if permission is not available or denied.
