### ISSUE TITLE
facing issue on android 5.0

### ISSUE THREAD

**Issue by arun1989** [pixo-vin/android-sdk#8]
java.lang.UnsatisfiedLinkError: No implementation found for void com.pixotech.android.scanner.library.service.LicenseKeyChecker.verifySDK(java.lang.String) (tried Java_com_pixotech_android_scanner_library_service_LicenseKeyChecker_verifySDK and Java_com_pixotech_android_scanner_library_service_LicenseKeyChecker_verifySDK__Ljava_lang_String_2)
This crash i am getting on only 5.0 but its working on 6.0 and 7 both.Please let me know if you have any solution.

**Comment by pixovin** [comment]
Hello and thank you for reporting this crash.

Our team is investigating and will respond with questions or next steps as
soon as possible.

Warmly,


*Shawna Culp*

Pixo *|* Business and Product Coordinator
121 W. Goose Alley
Urbana, IL 61801
(217) 344-0444
pixotech.com
pixoVIN.com

**Comment by youngest** [comment]
Hello,

What device and exact version of Android 5 are you running on? We have just tested on Android 5.0.1 (API 21) without issue. This may be an issue with a very specific build of Android, or it may be an issue with a specific device.

This error happens because the native JNI library packaged with our SDK has not been linked with your application at build time.

**Comment by arun1989** [comment]
I am using Samsung Note 3 Android version 5.0.

**Comment by arun1989** [comment]
FATAL EXCEPTION: main
                                                                        Process: com.ibcmobile.fasttrak, PID: 19266
                                                                        java.lang.UnsatisfiedLinkError: No implementation found for void com.pixotech.android.scanner.library.service.LicenseKeyChecker.verifySDK(java.lang.String) (tried Java_com_pixotech_android_scanner_library_service_LicenseKeyChecker_verifySDK and Java_com_pixotech_android_scanner_library_service_LicenseKeyChecker_verifySDK__Ljava_lang_String_2)
                                                                            at com.pixotech.android.scanner.library.service.LicenseKeyChecker.verifySDK(Native Method)
                                                                            at com.pixotech.android.scanner.library.service.LicenseKeyChecker.e(SourceFile:79)
                                                                            at com.pixotech.android.scanner.library.service.LicenseKeyChecker.c(SourceFile:59)
                                                                            at com.pixotech.android.scanner.library.BarcodeScanner.<init>(SourceFile:63)
                                                                            at com.pixotech.android.scanner.library.ScannerActivity.onCreate(SourceFile:24)
                                                                            at com.ibcmobile.fasttrak.ScanActivity.onCreate(ScanActivity.java:13)
                                                                            at android.app.Activity.performCreate(Activity.java:6283)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:177)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:145)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by pixovin** [comment]
Good morning,

Thank you for providing those additional details. We're still investigating
the issue and will update you as soon as possible.

Best,


*Shawna Culp*

Pixo *|* Business and Product Coordinator
121 W. Goose Alley
Urbana, IL 61801
(217) 344-0444
pixotech.com
pixoVIN.com

**Comment by youngest** [comment]
Is your Gradle file configured to create a different APK variant for different Android API levels? Or are you building from a different Gradle file for Android 5? This error means that the native JNI portion of the SDK is missing. If it is present in the app on Android 6 and 7 then it seems that something must be configured differently in your build for Android 5.

**Comment by pixovin** [comment]
Hello,

I wanted to follow up on your issue report. Has it resolved, or is there
additional information you can share to help in our troubleshooting?

Thanks in advance,


*Shawna Culp*

Pixo *|* Business and Product Coordinator
121 W. Goose Alley
Urbana, IL 61801
(217) 344-0444
pixotech.com
pixoVIN.com

**Comment by pixovin** [comment]
Hi,

It sounds like the issue was resolved so we're going to go ahead and close
this ticket, but please don't hesitate to reach out if we can help with
anything else.

Have a great weekend,


*Shawna Culp*

Pixo *|* Business and Product Coordinator
121 W. Goose Alley
Urbana, IL 61801
(217) 344-0444
pixotech.com
pixoVIN.com
